import { expect, test } from '@playwright/test';
import { mkdir } from 'node:fs/promises';

test('desktop icon dropdown works with hover, keyboard, outside click and real links', async ({ page }) => {
  test.slow();
  await mkdir('qa/navigation-dropdown', { recursive: true });
  await page.goto('/en/guides');
  const nav = page.getByRole('navigation', { name: 'Primary navigation' });
  const trigger = nav.getByRole('button', { name: 'Toggle Guides submenu' });
  await expect(trigger.locator('svg')).toHaveCount(1);
  await nav.getByRole('link', { name: 'Guides', exact: true }).hover();
  await expect(trigger).toHaveAttribute('aria-expanded', 'true');
  await expect(nav.getByRole('link', { name: 'Beginner Guide' })).toBeVisible();
  await page.screenshot({ path: 'qa/navigation-dropdown/desktop-open.png' });
  await page.keyboard.press('Escape');
  await expect(trigger).toHaveAttribute('aria-expanded', 'false');
  await expect(trigger).not.toBeFocused();
  await page.mouse.move(0, 500);
  await nav.getByRole('link', { name: 'Guides', exact: true }).hover();
  await expect(trigger).toHaveAttribute('aria-expanded', 'true');
  await page.mouse.move(0, 500);
  await expect(trigger).toHaveAttribute('aria-expanded', 'false');
  await trigger.focus();
  await trigger.press('Enter');
  await trigger.press('Tab');
  await expect(nav.getByRole('link', { name: 'Beginner Guide' })).toBeFocused();
  await page.keyboard.press('Escape');
  await expect(trigger).toBeFocused();
  await expect(trigger).toHaveAttribute('aria-expanded', 'false');
  await trigger.press('Space');
  await expect(trigger).toHaveAttribute('aria-expanded', 'true');
  await page.locator('h1').click();
  await expect(trigger).toHaveAttribute('aria-expanded', 'false');
  await nav.getByRole('link', { name: 'Game', exact: true }).hover();
  await nav.getByRole('link', { name: 'System Requirements', exact: true }).click();
  await expect(page).toHaveURL(/\/en\/game\/system-requirements$/);
  await page.getByRole('button', { name: 'Switch to dark theme' }).click();
  await nav.getByRole('link', { name: 'Game', exact: true }).hover();
  await expect(nav.getByRole('link', { name: 'System Requirements' })).toHaveAttribute('aria-current', 'page');
  await page.screenshot({ path: 'qa/navigation-dropdown/desktop-dark.png' });
});

test('mobile header shrinks, hides downward, returns upward and stays visible for an open menu', async ({ page }) => {
  await mkdir('qa/navigation-dropdown', { recursive: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/en/guides');
  const header = page.getByRole('banner');
  await expect(header).toHaveAttribute('data-compact', 'false');
  await page.evaluate(() => window.scrollTo({ top: 450, behavior: 'instant' }));
  await expect(header).toHaveAttribute('data-scroll-hidden', 'true');
  await expect.poll(async () => (await header.boundingBox())!.y + (await header.boundingBox())!.height).toBeLessThanOrEqual(0);
  await page.screenshot({ path: 'qa/navigation-dropdown/mobile-hidden.png' });
  expect(await page.evaluate(() => document.elementFromPoint(100, 20)?.closest('.site-header-slot') === null)).toBe(true);
  await page.evaluate(() => window.scrollTo({ top: 300, behavior: 'instant' }));
  await expect(header).toHaveAttribute('data-scroll-hidden', 'false');
  await expect(header).toHaveAttribute('data-compact', 'true');
  await page.getByRole('button', { name: 'Open navigation' }).click();
  await page.evaluate(() => window.scrollTo({ top: 700, behavior: 'instant' }));
  await expect(header).toHaveAttribute('data-scroll-hidden', 'false');
  const nav = page.getByRole('navigation', { name: 'Mobile navigation' });
  await nav.getByRole('button', { name: 'Toggle Game submenu' }).click();
  await expect(nav.getByRole('button', { name: 'Toggle Guides submenu' })).toHaveAttribute('aria-expanded', 'false');
  await expect(nav.getByRole('link', { name: 'Updates', exact: true })).toBeVisible();
  await page.screenshot({ path: 'qa/navigation-dropdown/mobile-open.png' });
  await nav.getByRole('link', { name: 'Updates', exact: true }).click();
  await expect(page).toHaveURL(/\/en\/updates$/);
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }));
  await expect(header).toHaveAttribute('data-compact', 'false');
  await expect(header).toHaveAttribute('data-scroll-hidden', 'false');
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(390);
});
